services:
  frontend:
    image: frontend
    container_name: algoespresso_frontend
    build:
      context: algoespresso_frontend
      dockerfile: dockerfile
      target: dev
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:3000/api/healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 3s
    depends_on:
      backend:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./algoespresso_frontend
          target: /app
          ignore:
            - .next
            - .clerk

    networks:
      - backend-frontend-net
    ports:
      - 3000:3000
    restart: unless-stopped

  backend:
    image: backend
    container_name: algoespresso_backend
    build:
      context: algoespresso_backend
      dockerfile: dockerfile
      target: dev
    networks:
      - backend-frontend-net
    healthcheck:
      test: [ "CMD", "/usr/src/app/bin/healthcheck" ]
      interval: 30s
      retries: 3
      start_period: 15s
      timeout: 5s
    ports:
      - 8080:8080
    restart: unless-stopped

networks:
  backend-frontend-net:

