#### BASE ####
FROM node:18-alpine AS base

ENV NEXT_TELEMETRY_DISABLED=1


#### INSTALL DEPENDENCIES ####
FROM base AS dev-deps

RUN apk add --no-cache libc6-compa

WORKDIR /app

# copy package manager files
COPY package.json package-lock.json ./

# install dependencies
RUN --mount=type=cache,target=/root/.npm npm clean-install


#### BUILD ####
FROM base AS dev-builder

WORKDIR /app

# copy installed dependencies
COPY --from=dev-deps /app/node_modules ./node_modules

# copy source code
COPY . .   

RUN npm run build


#==== DEV ====#
FROM base AS dev

WORKDIR /app

COPY --from=dev-builder /app/node_modules ./node_modules
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]